services:
  # https://hub.docker.com/_/composer
  composer:
    image: composer:2.2.4
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      COMPOSER_HOME: /.composer
    volumes:
      - ./:/app
      - ~/.composer:/.composer
    command: install

  # https://www.github.com/ideasonpurpose/docker-phpunit-watch
  test:
    image: ideasonpurpose/phpunit-watch:dev
    volumes:
      - ./:/app
