name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Prepare PHP Environment
      run: |
        apt update
        apt install -y libzip-dev unzip
        pecl install xdebug
        docker-php-ext-enable xdebug
        cp /usr/local/etc/php/php.ini-development /usr/local/etc/php/php.ini
        echo 'xdebug.mode=coverage' >> /usr/local/etc/php/php.ini

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run test suite
      run: vendor/bin/phpunit
      
    - name: Coddle Coveralls
      run: |
        mkdir -p build/logs
        cp coverage.xml build/logs/clover.xml

    - name: Upload to Coveralls
      env: 
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        COVERALLS_RUN_LOCALLY: yes
      run: |
        composer require --dev php-coveralls/php-coveralls
        vendor/bin/php-coveralls -v
