name: PHPUnit Test Coverage

on:
  push:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write

    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v6

      # https://github.com/marketplace/actions/setup-php-action
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Run test suite
        env:
          XDEBUG_MODE: coverage
        run: vendor/bin/phpunit

      # The Coveralls repo token is found on the project's Settings page
      # https://github.com/php-coveralls/php-coveralls
      - name: Upload to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
          COVERALLS_RUN_LOCALLY: yes
        run: |
          composer require 'php-coveralls/php-coveralls:2.7.0'
          vendor/bin/php-coveralls \
            --coverage_clover ./coverage.xml \
            --json_path ./coveralls-upload.json \
            --verbose

      # https://github.com/codecov/codecov-action
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: false
          files: ./coverage.xml
          verbose: true

      # https://github.com/qltysh/qlty-action
      - uses: qltysh/qlty-action/coverage@v2
        with:
          oidc: true
          files: coverage.xml
