name: Create Release from Version Tags

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  build:
    runs-on: ubuntu-24.04
    name: Build Release

    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v6

      # https://github.com/marketplace/actions/setup-php-action
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Create Zip archive
        id: create-zip-archive
        run: |
          composer archive -f zip --dir=../ --file=${{ github.event.repository.name }}
          echo "zip_path=../${{ github.event.repository.name }}.zip" >> $GITHUB_OUTPUT

      # - name: Create GitHub release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     gh release create "${{ github.ref_name }}" "${{ steps.create-zip-archive.outputs.zip_path }}"
